
title: The Clarity Lab
email: contact@claritylab.uk
description: >- # this means to ignore newlines until "baseurl:"
  The home of the Clarity Lab Method.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://claritylab.uk"
twitter_username: dug
github_username:  lrdj

# Moodboard pics
totalImages: 93

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed
  load_paths:
    - assets/govuk
    
# Workshop investment
investment_checkpoint: "£65.00"
investment_breakthrough: "£495.00"
investment_retreat: "£1,450.00"

# podcast
collections:
  podcasts:
    output: true
    permalink: /pod/:title/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/    # Keep this to prevent GitHub Pages from processing node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
